variables:
  - group : gcp-terraform-vars

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  displayName: 'Validation'
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          pwd 
          ls -ltr
          python3 -m pip install --upgrade pip
          pip3 install checkov
      displayName: 'Installing Checkov'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          checkov -d terraform
      displayName: 'Security Scan'

- stage: Plan
  jobs:
  - job: Plan
    steps:

    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'
    
    # - task: Bash@3
    #   displayName: Install Google Cloud SDK
    #   inputs:
    #     targetType: inline
    #     script: |
    #      curl https://sdk.cloud.google.com | bash
    #      source $HOME/google-cloud-sdk/path.bash.inc
    #      gcloud --version

    # - task: GCloud@0
    #   displayName: 'Authenticate to GCP'
    #   inputs:
    #     gcpServiceConnection: 'gcp-ado-pipeline'
    #     command: 'info'

    # - task: TerraformCLI@1
    #   displayName: 'Init'
    #   inputs:
    #     command: 'init'


    # - task: Bash@3
    #   displayName: 'init & Plan'
    #   inputs:
    #     targetType: 'inline'
    #     script: |

    #       cd terraform

    #       echo '$(GCP_KEY)' > gcp-key.json

    #       export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_GHA_CREDS_PATH

    #       terraform init -reconfigure \
    #       -backend-config="bucket=$(gcs_bucket)" \
    #       -backend-config="prefix=$(tfstate_prefix)"

    #       terraform plan -out=tfplan

    - task: Bash@3
      displayName: 'Debug Repo Structure'
      inputs:
        targetType: inline
        script: |
         echo "Current directory:"
         pwd
         echo "List all files recursively:"
         ls -R

    - task: Bash@3
      displayName: 'Terraform Init Plan'
      inputs:
        targetType: 'inline'
        script: |

         set -e

         cd ADO-pipeline-gcp
    
         echo "Current directory:"
         pwd

         echo "Files in directory:"
         ls -la

         echo "$(GCP_KEY)" > gcp-key.json
         export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json

         terraform version

         terraform init -reconfigure \
         -backend-config="bucket=$(gcs_bucket)" \
         -backend-config="prefix=$(tfstate_prefix)"

         terraform fmt -check
         terraform validate

         terraform plan -out=tfplan