variables:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.6'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          pwd 
          ls -ltr
          python3 -m pip install --upgrade pip
          pip3 install checkov
      displayName: 'Installing Checkov'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          checkov -d terraform
      displayName: 'Security Scan'

- stage: Plan
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:

    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.6'

    # - task: Bash@3
    #   displayName: 'Debug Repo Structure'
    #   inputs:
    #     targetType: inline
    #     script: |
    #      echo "Current directory:"
    #      pwd
    #      echo "List all files recursively:"
    #      ls -R

    - task: DownloadSecureFile@1
      name: gcpcred
      inputs:
        secureFile: gcp-wif.json

    - script: |
       echo "Exporting credentials"
       export GOOGLE_APPLICATION_CREDENTIALS=$(gcpcred.secureFilePath)
       gcloud auth list
      displayName: Test GCP Authentication

    # - task: Bash@3
    #   displayName: 'Terraform Init Plan'
    #   inputs:
    #     targetType: 'inline'
    #     script: |

    

    #       terraform init -reconfigure
    #       terraform plan -out=tfplan

    # - publish: tfplan
    #   artifact: terraform-plan