#Validate
#  ↓
#Checkov Security Scan
#  ↓
#Terraform Init
#  ↓
#Terraform Plan (creates tfplan)
#   ↓
#Publish tfplan artifact
#   ↓
#Apply Stage
#   ↓
#Download artifact
#   ↓
#Terraform Apply

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.6'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          pwd 
          ls -ltr
          python3 -m pip install --upgrade pip
          pip3 install checkov
      displayName: 'Installing Checkov'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          checkov -d terraform
      displayName: 'Security Scan'

- stage: Plan
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:

    - checkout: self
      
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.6'

    - task: DownloadSecureFile@1
      name: gcpcred
      inputs:
        secureFile: gcp-wif.json

    - bash: |
        echo "Requesting OIDC token from Azure DevOps..."

        curl -s \
         -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
         "https://vstoken.dev.azure.com/syedafzalsh/_apis/distributedtask/hubs/build/plans/$SYSTEM_PLANID/jobs/$SYSTEM_JOBID/oidctoken?api-version=7.1-preview.1" \
         | jq -r '.oidcToken' > /tmp/oidc-token

        export GOOGLE_APPLICATION_CREDENTIALS=$(gcpcred.secureFilePath)

        gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS

        echo "Authenticated accounts:"
        gcloud auth list
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        SYSTEM_PLANID: $(System.PlanId)
        SYSTEM_JOBID: $(System.JobId)
      displayName: Authenticate to GCP

    - task: Bash@3
      displayName: 'Terraform Init Plan'
      inputs:
        targetType: 'inline'
        script: |
         terraform init -reconfigure
         terraform plan -out=tfplan
      env:
         GOOGLE_APPLICATION_CREDENTIALS: $(GOOGLE_APPLICATION_CREDENTIALS)

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'tfplan'
        artifact: 'terraform-plan'

# - stage: Apply
#   dependsOn: Plan
#   jobs:
#   - job: Apply
#     steps:

#     - checkout: self

#     - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
#       inputs:
#        terraformVersion: '1.14.6'

#     - task: DownloadSecureFile@1
#       name: gcpcred
#       inputs:
#         secureFile: gcp-wif.json

#     - bash: |
#         echo "Requesting OIDC token from Azure DevOps..."

#         curl -s \
#          -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
#          "https://vstoken.dev.azure.com/syedafzalsh/_apis/distributedtask/hubs/build/plans/$SYSTEM_PLANID/jobs/$SYSTEM_JOBID/oidctoken?api-version=7.1-preview.1" \
#          | jq -r '.oidcToken' > /tmp/oidc-token

#         export GOOGLE_APPLICATION_CREDENTIALS=$(gcpcred.secureFilePath)

#         gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS

#         echo "Authenticated accounts:"
#         gcloud auth list
#       env:
#         SYSTEM_ACCESSTOKEN: $(System.AccessToken)
#         SYSTEM_PLANID: $(System.PlanId)
#         SYSTEM_JOBID: $(System.JobId)
#       displayName: Authenticate to GCP

#     - download: current
#       artifact: terraform-plan

#     - task: Bash@3
#       displayName: Terraform Init
#       inputs:
#         targetType: inline
#         script: |
#           terraform init -reconfigure
#       env:
#         GOOGLE_APPLICATION_CREDENTIALS: $(GOOGLE_APPLICATION_CREDENTIALS)

#     - task: Bash@3
#       displayName: Terraform Apply
#       inputs:
#         targetType: inline
#         script: |
#           terraform apply -auto-approve $(Pipeline.Workspace)/terraform-plan/tfplan
#       env:
#         GOOGLE_APPLICATION_CREDENTIALS: $(GOOGLE_APPLICATION_CREDENTIALS) 